name: Flutter Analyze

on: [pull_request]

permissions:
  contents: read
  pull-requests: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Flutter_Analyzer:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3.14.0
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.3
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Analyze
        run: flutter analyze
